project:
  type: website
  output-dir: docs

website:
  title: "TONe Integrated Cloud Observatory"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



